version: "3"
services:
    backend:
        container_name: portscanner-backend
        restart: on-failure
        build: .
        ports:
            - "8000:8000"
        environment: 
            - PORT=${PORT}
            - WHITELIST=${WHITELIST}
            - SECRET=${SECRET}
            - SALT_ROUNDS=${SALT_ROUNDS}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - MODE=production
            - NODE_ENV=production
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=portscanner
    frontend:
        container_name: portscanner-frontend
        image: tfgportscanner/portscanner-frontend:1.0.0
        ports:
            - "8002:80"